### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by smile68** [Socialz/lua-mta-fairplay#11]
у меня tab не работает и вообще как найти работы админка на половину работает

**Comment by smile68** [comment]
и пикапы входа не работают

**Comment by Socialz** [comment]
It is difficult for me to help you since you are writing Russian, and translations do not work properly.

**Comment by smile68** [comment]
ладно вот проблема у меня tab не работает, пикапов нет, работу тоже не показывает не могли бы вы выложить mtaserver cвой настроенный и acl

**Comment by smile68** [comment]
okay here's the problem my tab does not work, no pickups, the work also shows could you put mtaserver your customized and acl

**Comment by smile68** [comment]
now I have
<acl>
	<group name="Everyone">
		<acl name="Default" />
		<object name="user.*" />
	</group>
	<group name="Moderator">
		<acl name="Moderator" />
	</group>
	<group name="SuperModerator">
		<acl name="Moderator" />
		<acl name="SuperModerator" />
	</group>
	<group name="Admin">
		<acl name="Moderator" />
		<acl name="SuperModerator" />
		<acl name="Admin" />
		<acl name="RPC" />
		<object name="resource.*" />
	</group>
	<group name="Console">
		<acl name="Moderator" />
		<acl name="SuperModerator" />
		<acl name="Admin" />
		<acl name="RPC" />
		<object name="user.Console" />
	</group>
	<group name="RPC">
		<acl name="RPC" />
	</group>
	<group name="MapEditor">
		<acl name="Default" />
		<acl name="MapEditor" />
	</group>
	<group name="raceACLGroup">
		<acl name="Default" />
		<acl name="raceACL" />
	</group>
	<group name="DevGroup">
		<acl name="DevACL" />
	</group>
	<acl name="Default">
		<right name="general.ModifyOtherObjects" access="false" />
		<right name="general.http" access="false" />
		<right name="command.start" access="false" />
		<right name="command.stop" access="false" />
		<right name="command.stopall" access="false" />
		<right name="command.gamemode" access="false" />
		<right name="command.changemode" access="false" />
		<right name="command.changemap" access="false" />
		<right name="command.stopmode" access="false" />
		<right name="command.stopmap" access="false" />
		<right name="command.skipmap" access="false" />
		<right name="command.restart" access="false" />
		<right name="command.refresh" access="false" />
		<right name="command.refreshall" access="false" />
		<right name="command.addaccount" access="false" />
		<right name="command.delaccount" access="false" />
		<right name="command.debugscript" access="false" />
		<right name="command.chgpass" access="false" />
		<right name="command.loadmodule" access="false" />
		<right name="command.upgrade" access="false" />
		<right name="command.mute" access="false" />
		<right name="command.crun" access="false" />
		<right name="command.srun" access="false" />
		<right name="command.run" access="false" />
		<right name="command.unmute" access="false" />
		<right name="command.kick" access="false" />
		<right name="command.ban" access="false" />
		<right name="command.banip" access="false" />
		<right name="command.unbanip" access="false" />
		<right name="command.reloadbans" access="false" />
		<right name="command.shutdown" access="false" />
		<right name="command.install" access="false" />
		<right name="command.aexec" access="false" />
		<right name="command.whois" access="false" />
		<right name="command.whowas" access="false" />
		<right name="command.aclrequest" access="false" />
		<right name="function.executeCommandHandler" access="false" />
		<right name="function.setPlayerMuted" access="false" />
		<right name="function.addAccount" access="false" />
		<right name="function.addBan" access="false" />
		<right name="function.removeBan" access="false" />
		<right name="function.removeAccount" access="false" />
		<right name="function.setAccountPassword" access="false" />
		<right name="function.kickPlayer" access="false" />
		<right name="function.banIP" access="false" />
		<right name="function.banPlayer" access="false" />
		<right name="function.banSerial" access="false" />
		<right name="function.getBansXML" access="false" />
		<right name="function.unbanIP" access="false" />
		<right name="function.unbanSerial" access="false" />
		<right name="function.reloadBans" access="false" />
		<right name="function.setServerPassword" access="false" />
		<right name="function.getServerPassword" access="false" />
		<right name="function.callRemote" access="false" />
		<right name="function.fetchRemote" access="false" />
		<right name="function.startResource" access="false" />
		<right name="function.stopResource" access="false" />
		<right name="function.restartResource" access="false" />
		<right name="function.createResource" access="false" />
		<right name="function.copyResource" access="false" />
		<right name="function.addResourceMap" access="false" />
		<right name="function.addResourceConfig" access="false" />
		<right name="function.removeResourceFile" access="false" />
		<right name="function.setResourceDefaultSetting" access="false" />
		<right name="function.removeResourceDefaultSetting" access="false" />
		<right name="function.redirectPlayer" access="false" />
		<right name="function.aclReload" access="false" />
		<right name="function.aclSave" access="false" />
		<right name="function.aclCreate" access="false" />
		<right name="function.aclDestroy" access="false" />
		<right name="function.aclSetRight" access="false" />
		<right name="function.aclRemoveRight" access="false" />
		<right name="function.aclCreateGroup" access="false" />
		<right name="function.aclDestroyGroup" access="false" />
		<right name="function.aclGroupAddACL" access="false" />
		<right name="function.aclGroupRemoveACL" access="false" />
		<right name="function.aclGroupAddObject" access="false" />
		<right name="function.aclGroupRemoveObject" access="false" />
		<right name="function.refreshResources" access="false" />
		<right name="function.setServerConfigSetting" access="false" />
		<right name="function.updateResourceACLRequest" access="false" />
	</acl>
	<acl name="Moderator">
		<right name="general.ModifyOtherObjects" access="false" />
		<right name="command.gamemode" access="true" />
		<right name="command.changemode" access="true" />
		<right name="command.changemap" access="true" />
		<right name="command.stopmode" access="true" />
		<right name="command.stopmap" access="true" />
		<right name="command.skipmap" access="true" />
		<right name="command.mute" access="true" />
		<right name="command.unmute" access="true" />
		<right name="command.whois" access="true" />
		<right name="command.whowas" access="true" />
		<right name="function.setPlayerMuted" access="true" />
		<right name="function.kickPlayer" access="true" />
		<right name="function.banIP" access="true" />
		<right name="function.banPlayer" access="true" />
		<right name="function.banSerial" access="true" />
		<right name="function.getBansXML" access="true" />
		<right name="function.unbanIP" access="true" />
		<right name="function.unbanSerial" access="true" />
		<right name="function.startResource" access="true" />
		<right name="function.stopResource" access="true" />
		<right name="function.restartResource" access="true" />
		<right name="function.redirectPlayer" access="true" />
	</acl>
	<acl name="SuperModerator">
		<right name="general.ModifyOtherObjects" access="false" />
		<right name="command.start" access="true" />
		<right name="command.stop" access="true" />
		<right name="command.restart" access="true" />
		<right name="command.kick" access="true" />
		<right name="command.ban" access="true" />
		<right name="command.banip" access="true" />
		<right name="command.unbanip" access="true" />
		<right name="command.reloadbans" access="true" />
		<right name="command.refresh" access="true" />
		<right name="command.refreshall" access="true" />
		<right name="command.loadmodule" access="true" />
		<right name="command.addaccount" access="true" />
		<right name="command.delaccount" access="true" />
		<right name="command.chgpass" access="true" />
		<right name="function.addAccount" access="true" />
		<right name="function.removeAccount" access="true" />
		<right name="function.setAccountPassword" access="true" />
	</acl>
	<acl name="Admin">
		<right name="general.ModifyOtherObjects" access="true" />
		<right name="general.http" access="true" />
		<right name="general.*" access="true" />
		<right name="command.shutdown" access="true" />
		<right name="command.install" access="true" />
		<right name="command.aexec" access="true" />
		<right name="command.debugscript" access="true" />
		<right name="command.upgrade" access="true" />
		<right name="command.crun" access="true" />
		<right name="command.srun" access="true" />
		<right name="command.run" access="true" />
		<right name="command.run" access="*" />
		<right name="function.addBan" access="true" />
		<right name="function.removeBan" access="true" />
		<right name="function.reloadBans" access="true" />
		<right name="function.executeCommandHandler" access="true" />
		<right name="function.setServerPassword" access="true" />
		<right name="function.getServerPassword" access="true" />
		<right name="function.createResource" access="true" />
		<right name="function.copyResource" access="true" />
		<right name="function.addResourceMap" access="true" />
		<right name="function.addResourceConfig" access="true" />
		<right name="function.removeResourceFile" access="true" />
		<right name="function.setResourceDefaultSetting" access="true" />
		<right name="function.removeResourceDefaultSetting" access="true" />
		<right name="function.aclReload" access="true" />
		<right name="function.aclSave" access="true" />
		<right name="function.aclCreate" access="true" />
		<right name="function.aclDestroy" access="true" />
		<right name="function.aclSetRight" access="true" />
		<right name="function.aclRemoveRight" access="true" />
		<right name="function.aclCreateGroup" access="true" />
		<right name="function.aclDestroyGroup" access="true" />
		<right name="function.aclGroupAddACL" access="true" />
		<right name="function.aclGroupRemoveACL" access="true" />
		<right name="function.aclGroupAddObject" access="true" />
		<right name="function.aclGroupRemoveObject" access="true" />
		<right name="function.refreshResources" access="true" />
		<right name="function.setServerConfigSetting" access="true" />
		<right name="function.updateResourceACLRequest" access="true" />
		<right name="function.*" access="true" />
		<right name="command.aclrequest" access="true" />
	</acl>
	<acl name="RPC">
		<right name="function.callRemote" access="true" />
		<right name="function.fetchRemote" access="true" />
	</acl>
	<acl name="MapEditor">
		<right name="general.ModifyOtherObjects" access="true" />
		<right name="function.startResource" access="true" />
		<right name="function.stopResource" access="true" />
		<right name="function.restartResource" access="true" />
		<right name="function.createResource" access="true" />
		<right name="function.copyResource" access="true" />
		<right name="function.renameResource" access="true" />
		<right name="function.deleteResource" access="true" />
		<right name="function.addResourceMap" access="true" />
		<right name="function.addResourceConfig" access="true" />
		<right name="function.removeResourceFile" access="true" />
		<right name="function.setResourceDefaultSetting" access="true" />
		<right name="function.removeResourceDefaultSetting" access="true" />
		<right name="function.xmlLoadFile" access="true" />
	</acl>
	<acl name="raceACL">
		<right name="general.ModifyOtherObjects" access="true" />
		<right name="function.xmlLoadFile" access="true" />
		<right name="function.startResource" access="true" />
		<right name="function.stopResource" access="true" />
		<right name="function.restartResource" access="true" />
	 </acl>
	<acl name="DevACL">
		  <right name="resource.performancebrowser.http" access="true"></right>
		  <right name="resource.ajax.http" access="true"></right>
	</acl>
</acl>

**Comment by smile68** [comment]
I have the "acl" folder configurations

**Comment by Socialz** [comment]
I will put my copy of my mtaserver.conf and acl.xml here in a moment.

Also, the HUD is meant to not show life, armor or money.

**Comment by smile68** [comment]
![mta-screen_2015-01-13_15-18-58](https://cloud.githubusercontent.com/assets/10502874/5721118/9470462c-9b3e-11e4-923f-f84fb92d2331.png)

**Comment by smile68** [comment]
![mta-screen_2015-01-13_15-22-17](https://cloud.githubusercontent.com/assets/10502874/5721227/012bf58a-9b40-11e4-8736-8c5facdaa159.png)

**Comment by Socialz** [comment]
Yes. HUD is not meant to be there for a reason. It is role play script, you use commands to see things like money (/wallet). Health and armor is not relevant, as you roleplay your health. Armor is not properly scripted in, so armor is irrelevant as well. Location can be seen through the GPS item.

Interior markers you have to make yourself with admin commands (/createinterior).

https://github.com/Socialz/lua-mta-fairplay/blob/master/resources/roleplay-admin/c_admin.lua

**Comment by smile68** [comment]
thank
I'm just a noob still )

    
    
    
    
    
    <resource src="admin" startup="1" protected="0" />
    <resource src="defaultstats" startup="1" protected="0" />
    <resource src="helpmanager" startup="1" protected="0" />
    <resource src="joinquit" startup="1" protected="0" />
    <resource src="mapcycler" startup="1" protected="0" />
    <resource src="mapmanager" startup="1" protected="0" />
    <resource src="parachute" startup="1" protected="0" />
    <resource src="resourcebrowser" startup="1" protected="1" default="true" />
    <resource src="resourcemanager" startup="1" protected="1" />
    <resource src="scoreboard" startup="1" protected="0" />
    <resource src="spawnmanager" startup="1" protected="0" />
    <resource src="voice" startup="1" protected="0" />
    <resource src="votemanager" startup="1" protected="0" />
    <resource src="webadmin" startup="1" protected="0" />
    <resource src="webmap" startup="1" protected="0" />
    
    
    
    <resource src="initializer" startup="1" protected="0" />
    
    <resource src="pak22" startup="1" protected="0" />
</config>





right?

**Comment by Socialz** [comment]
Only this:

```
<resource src="roleplay-initializer" startup="1" protected="0" />
<resource src="pak22" startup="1" protected="0" />
```

**Comment by smile68** [comment]
and spare no? or what did not finish just recently I have included pickups but right now there is something can be removed?
