### ISSUE TITLE
Cannot start the gamemode

### ISSUE THREAD

**Issue by AlphabetoPT** [Socialz/lua-mta-fairplay#14]
error log:

http://pastebin.com/c9Q2cWdt

**Comment by Citizen01** [comment]
As the error logs says, the resources don't have the admin permissions (Access denied).
Did you even read the installation instructions ???
> You might also have to set all resources in the admin ACL group in the acl.xml file in the /deathmatch folder of your server. This way you will avoid issues with remote connections and such. You may use the included acl.xml file for that instead of figuring it out yourself but I do not guarantee security for that.

Here is how your acl should looks like: 
```xml
<acl>
    [...]
    <group name="Admin">
        <acl name="Moderator"></acl>
        <acl name="SuperModerator"></acl>
        <acl name="Admin"></acl>
        <acl name="RPC"></acl>
        <object name="resource.admin"></object>
        <object name="resource.webadmin"></object>
		[...]
        <object name="resource.roleplay-accounts"></object>
        <object name="resource.roleplay-admin"></object>
        <object name="resource.roleplay-animations"></object>
        <object name="resource.roleplay-anticheat"></object>
        <object name="resource.roleplay-banking"></object>
        <object name="resource.roleplay-chat"></object>
        <object name="resource.roleplay-dmv"></object>
        <object name="resource.roleplay-dofbokeh"></object>
        <object name="resource.roleplay-donators"></object>
        <object name="resource.roleplay-drugs"></object>
        <object name="resource.roleplay-emergency"></object>
        <object name="resource.roleplay-factions"></object>
        <object name="resource.roleplay-fancy"></object>
        <object name="resource.roleplay-gates"></object>
        <object name="resource.roleplay-gearbox"></object>
        <object name="resource.roleplay-initializer"></object>
        <object name="resource.roleplay-interiors"></object>
        <object name="resource.roleplay-inventory"></object>
        <object name="resource.roleplay-items"></object>
        <object name="resource.roleplay-jobs"></object>
        <object name="resource.roleplay-logging"></object>
        <object name="resource.roleplay-maps"></object>
        <object name="resource.roleplay-notifications"></object>
        <object name="resource.roleplay-pd"></object>
        <object name="resource.roleplay-phone"></object>
        <object name="resource.roleplay-realism"></object>
        <object name="resource.roleplay-scoreboard"></object>
        <object name="resource.roleplay-settings"></object>
        <object name="resource.roleplay-shaders"></object>
        <object name="resource.roleplay-shop"></object>
        <object name="resource.roleplay-utilities"></object>
        <object name="resource.roleplay-vehiclefuel"></object>
        <object name="resource.roleplay-vehiclesnodes"></object>
        <object name="resource.roleplay-vehicles"></object>
        <object name="resource.roleplay-vehicleshop"></object>
        <object name="resource.roleplay-weapons"></object>
        <object name="resource.roleplay-weather"></object>
        <object name="resource.mapSystem"></object>
        <object name="resource.derbyArena"></object>
        <object name="resource.avatarSystem"></object>
        <object name="resource.commonSystem"></object>
        <object name="resource.dashboardSystem"></object>
        <object name="resource.scriptsSystem"></object>
    </group>
    [...]
</acl>
```
(**Note:** Do not copy the "[...]", it's just to shows there are other tags there I removed in this answer)
Simply copy all `<object name="resource.roleplay-XXXXX"></object>` above and paste them in your **Admin acl group**, start the server and it will work (if you did all others installation steps already).

Best regards,
Citizen

**Comment by Citizen01** [comment]
As the error logs says, the resources don't have the admin permissions (Access denied).
Did you even read the installation instructions ???
> You might also have to set all resources in the admin ACL group in the acl.xml file in the /deathmatch folder of your server. This way you will avoid issues with remote connections and such. You may use the included acl.xml file for that instead of figuring it out yourself but I do not guarantee security for that.

Here is how your acl should looks like: 
```xml
<acl>
    [...]
    <group name="Admin">
        <acl name="Moderator"></acl>
        <acl name="SuperModerator"></acl>
        <acl name="Admin"></acl>
        <acl name="RPC"></acl>
        <object name="resource.admin"></object>
        <object name="resource.webadmin"></object>
		[...]
        <object name="resource.roleplay-accounts"></object>
        <object name="resource.roleplay-admin"></object>
        <object name="resource.roleplay-animations"></object>
        <object name="resource.roleplay-anticheat"></object>
        <object name="resource.roleplay-banking"></object>
        <object name="resource.roleplay-chat"></object>
        <object name="resource.roleplay-dmv"></object>
        <object name="resource.roleplay-dofbokeh"></object>
        <object name="resource.roleplay-donators"></object>
        <object name="resource.roleplay-drugs"></object>
        <object name="resource.roleplay-emergency"></object>
        <object name="resource.roleplay-factions"></object>
        <object name="resource.roleplay-fancy"></object>
        <object name="resource.roleplay-gates"></object>
        <object name="resource.roleplay-gearbox"></object>
        <object name="resource.roleplay-initializer"></object>
        <object name="resource.roleplay-interiors"></object>
        <object name="resource.roleplay-inventory"></object>
        <object name="resource.roleplay-items"></object>
        <object name="resource.roleplay-jobs"></object>
        <object name="resource.roleplay-logging"></object>
        <object name="resource.roleplay-maps"></object>
        <object name="resource.roleplay-notifications"></object>
        <object name="resource.roleplay-pd"></object>
        <object name="resource.roleplay-phone"></object>
        <object name="resource.roleplay-realism"></object>
        <object name="resource.roleplay-scoreboard"></object>
        <object name="resource.roleplay-settings"></object>
        <object name="resource.roleplay-shaders"></object>
        <object name="resource.roleplay-shop"></object>
        <object name="resource.roleplay-utilities"></object>
        <object name="resource.roleplay-vehiclefuel"></object>
        <object name="resource.roleplay-vehiclesnodes"></object>
        <object name="resource.roleplay-vehicles"></object>
        <object name="resource.roleplay-vehicleshop"></object>
        <object name="resource.roleplay-weapons"></object>
        <object name="resource.roleplay-weather"></object>
        <object name="resource.mapSystem"></object>
        <object name="resource.derbyArena"></object>
        <object name="resource.avatarSystem"></object>
        <object name="resource.commonSystem"></object>
        <object name="resource.dashboardSystem"></object>
        <object name="resource.scriptsSystem"></object>
    </group>
    [...]
</acl>
```
(**Note:** Do not copy the "[...]", it's just to shows there are other tags there I removed in this answer)
Simply copy all `<object name="resource.roleplay-XXXXX"></object>` above and paste them in your **Admin acl group**, start the server and it will work (if you did all others installation steps already).

Best regards,
Citizen

**Comment by AlphabetoPT** [comment]
Nope. it was about the libs.
That step is done now.

Im am having issues creating a character. It allways says my nick name 
must be 2chars long and less than 25 but never proceed.

Skype..: mcaleatorio
TS3..: ts.zionportugal.com (i am owner - AlphabetoPT)

please try to answer today bro..

Thanks

**Comment by AlphabetoPT** [comment]
Ok. i was into code and i notice that you should have a space between 
first and last name to character.
I changed the error in order to make it more understandable.

I still need your help but now the step is easier  guess.
you forgot to send the sql dumps to load the table for weather...
i really would lofe the rows needed.

i think i'll love your mod.
i will try to add jobs and let u know bro
thanks

**Comment by AlphabetoPT** [comment]
Also the tables that came with MOD are empty. Can you provide-me some?
i guess i am asking too much :P

**Comment by Socialz** [comment]
Of course they are empty. What would you expect?

Weather does not have anything to do with SQL.

**Comment by AlphabetoPT** [comment]
i am already running it.
edititing the existing table.


Can you tell me how do i set vehicle spawn for newbies?

**Comment by AlphabetoPT** [comment]
Yes it as to do with sql what are u saing?


"[01:02:56] Admin access list successfully updated
[01:02:56] INFO: Admin added 427 missing rights
[01:02:56] Server minclientversion is now 1.4.0-9.07060
[01:02:56] Initializing account resource.
[01:02:56] Notice: MySQL connection is established!
[01:02:56] Notice: Connection is working!
[01:02:56] ERROR: roleplay-accounts/s_webserver.lua:85:"


the connection made to the second table on file s_webserver.lua
am i mistaken?

if so... please help

i am quite experienced with bukkit and Minecraft itself. i owned servers 
like for ages... but this is whole a new camp for me... i will be better 
in the next couple of days.

Cheers

**Comment by Socialz** [comment]
You can find the admin commands by using the /ah command (or by reading through here: https://github.com/Socialz/lua-mta-fairplay/blob/master/resources/roleplay-admin/c_admin.lua).

You can use the same connection on the s_webserver.lua as you do with your normal connection. The tables it uses are in the same SQL dump, anyway.

**Comment by AlphabetoPT** [comment]
I got it. Is there anyway to talk with you? I would Like to discuss some
things with you
Em 11/03/2015 14:14, "Socialz" <notifications@github.com> escreveu:

**Comment by AlphabetoPT** [comment]
Where do i turn off the vehicles?

**Comment by AlphabetoPT** [comment]
Are u there?

**Comment by AlphabetoPT** [comment]
are u there bro?

**Comment by Socialz** [comment]
What do you mean by "turn off vehicles"?

And this is not a chat, so do not spam it please.

**Comment by AlphabetoPT** [comment]
that's why i asked you another place to talk.
i guess i will not use your gamemode because it's not explained well bro.
There's not even a list of full commands.
vehicle shops are bugged.
vehicles are bugged since you cannot enter spawned vehicles with admin 
panel.
they are with the engine turned off and no keyboard key will turn it on,,,

**Comment by Socialz** [comment]
Okay. That's because roleplay is exactly like that. You cannot use any other scripts such as the default admin panel in conjunction with this, because they do not work together.

Like I said, you can use /ah -command to view the commands, or the lua file referenced above.

**Comment by AlphabetoPT** [comment]
ok my bad. sorry you have already sent me the commands and i was 
''sleeping''

but i guess this one is a bug. i bought a vehicle on the shop and i cant 
use it. why?
the bike keeps floating. allow me to enter the veh but not to use it. why?

**Comment by AlphabetoPT** [comment]
Regarding to vehicles.
When i use /makecivveh 420 2
it spawns a BLACK taxi with green zeros above it.
When i enter the veh i still cant drive it. why?

and how do i create a taxi HQ. like a marker when u go through it you 
become taxi driver

**Comment by AlphabetoPT** [comment]
Also. is there a way to place marks on map?

**Comment by Socialz** [comment]
You can add more blips to the map through this file: https://github.com/Socialz/lua-mta-fairplay/blob/master/resources/roleplay-accounts/s_game.lua

To read the documentation on how to use createBlip, read this: http://wiki.multitheftauto.com/wiki/CreateBlip

You have a couple basic controls on vehicles:
J = toggle engine on/off
K = toggle lock on/off
L = toggle lights on/off
/handbrake = toggle handbrake on/off

These will get you started with vehicles.

**Comment by AlphabetoPT** [comment]
Thanks bro.
Other thing. What is the ID to city hall? i cant find it in interiors lua file. 
thanks

**Comment by Socialz** [comment]
City Hall does not have its own ID. You have to use one of the interiors provided in the *roleplay-interiors/s_interiors.lua* file.

**Comment by AlphabetoPT** [comment]
Thank you very much.
How about the HQ for taxi for instance. is it hard to program?

**Comment by AlphabetoPT** [comment]
P.s i am altering your lua files i hope you dont get mad on it :)
i managed to add City Hall :) its working. i would really like to 'talk' with you by voice or chat on TS or Skype.

This is because i have some questions ofc but if i talk to you about 20m i will need no more help in future i guess. 

thanks

**Comment by Socialz** [comment]
I do not have an answer to your first question. It is up to your own skill whether or not is it easy to script or not. I am not altering this gamemode anymore, because it is old and I am working on a new one.

You are allowed to alter your copy of the gamemode as much as you like. This is allowed even in the license shipped with the gamemode, so, no worries.

I am not available on any chat at this time. If you have any further questions, issues or problems that you want me to look into, feel free to report them on this issue board.

**Comment by AlphabetoPT** [comment]
Thanks I will keep in touch :)
I managed to place a bank too.. however there's no doors. LOL
i guess this is not a really bank without any doors. is there anyway to create this missing doors?

anyway if you want to check just ask the IP adress,

**Comment by AlphabetoPT** [comment]
What about players commands? where do i find them?

**Comment by Socialz** [comment]
You can add doors in Map Editor, and then apply them with /gates.

There are no player commands. There are only a couple features, which are either bound to some function keys (e.g. F2, F3, F10) and tab.

**Comment by Socialz** [comment]
And then obviously the inventory with the I key.

**Comment by AlphabetoPT** [comment]
Last time i used map editor i messed things up.
my atms disappeared. i needed to reinstall full gamemode and start from 
scratch that was not a good thing.

what is the procedure to correctly add things to map without loosing any 
stuff already added?

**Comment by AlphabetoPT** [comment]
believe me i try not to spam. but there's no other way to do this xD

Question 2 (question 1 is on the post above)
Is there a way to add pedestrians or just by adding fuelstations?

by the way. you forgot to add /makefuelst or something like that :) if you guide-me i can add this :) 
love you bro. 
i used to run MC servers as i said yesterday. I will insert a paymentwall API so people can buy VIP and ingame cash.

I will defenitly love to share my profits with you giving you access to paymentwall reports.
i dont want anything in return besides some questions. I changed to MTA because i want to learn LUNA and not to have people working for me =)

this is a proposal to something closer to a society :)

**Comment by AlphabetoPT** [comment]
Question #3 what should i do to enable DMV?
thanks

**Comment by AlphabetoPT** [comment]
Forget other posts except my kinda proposal :P

Ok let me update my status. 
I have now figured out how to make fuelstations and shops by commands (both commands were missing in /ah) yea... i've been reading most part of your code :) nicely done i should say. huge work :)

what i am missing now:

#1 Is there a way to add simple Pedestrians Stopped, not moving around. Like you have on Police LS for instance.
#2 How do i activate DMV?
#3 i cant use my cellphone. It keeps saying the number i am trying to dial is not in use.
#4 I would love to see server time on GTA original Clock if possible.
#5 Life bar and currently equiped weapon too
#6 How do i put ammunations to work? cant find it anywere (and i looked hard,  maybe not hard enough)
#7 That thing with vehicle shops... i bought a Bike and i cant take it nowere. the bike keeps flying and even crashing against it with a car does not debug it. I have been reading vehicleshop lua files and i cant find the node where you make the bike real after bought. maybe it's a Z-axis missconfiguration or am i missing something?

I will keep other questions for later (because i really dont get more by now)
Cheers bro.

**Comment by Socialz** [comment]
*1.* You can make an empty shop, for example. To do this, you can add an empty shop to *roleplay-shops/c_shop.lua* **tabs** table like the following:

`
[ 2 ] = {
		name	= "NPC",
		itemID	= { },
		price		= { }
	}
`

And then add it server-side to the **roleplay-shops/s_shop.lua** like this:

`
local shopids = { [ 1 ] = 1, [ 2 ] = 2 }
local workskins = { { 211, 217 }, { 211, 217 } }
`

You can find skin IDs here: http://wiki.multitheftauto.com/wiki/All_Skins_Page.

*2.* At the top of that file you can find a variable for `isEnabled`. Turn this to `true` instead of `false`. However, keep in mind that this system was never finished and will most likely bug out.

*3.* Make sure that phone number exists?

*4.* It is, as far as I know. If you cannot see the clock, then apply the following to line 625 of the **roleplay-accounts/s_accounts.lua** file.

`
setPlayerHudComponentVisible( client, "clock", true )
`

*5.* You can enable these by adding these to line 625 of the **roleplay-accounts/s_accounts.lua** file.

`
setPlayerHudComponentVisible( client, "weapon", true )
setPlayerHudComponentVisible( client, "health", true )
`

*6.* Weapons were never properly implemented into this script.

*7.* Use the /handbrake command.

*8.* You need to run Map Editor via the main menu of MTA. You cannot start it on your roleplay server, it will most likely break things.

*9.* You can use the /call, /pickup, /hangup commands with cellphones. There are not too many commands for players, which is why I never listed them.

*10.* I cannot help you with this, because your idea is not serving the idea of this script. This script is solely for roleplay purposes, where money is everything from purchasing a chocolate bar to managing a huge corporation. Random cars do not serve the idea of roleplay, and I do not support that with this gamemode. I like the idea, but this script is not meant for that really. You are free to make it like that if you wish, but I won't be able to help you. You can edit the vehicle shops in the **roleplay-vehicleshop/s_vehicleshop.lua** file.

**Comment by AlphabetoPT** [comment]
Hi bro. 

#1 Phones are not working. I tried with friends. I guess the thing is the first number of Phone starts by 0 when you mouse over on cellphone icon in the inventory it says: #046038 but they cant call me to 046038 or to 46038. When i open phone it says number is 46038 and none of the numbers work.

#2 DMV is bugged. i ask your attention to this code.: ( i dont know how to make code quotes in here if you can show me the way i would appreciate.)

CODE: 
addEventHandler("onClientResourceStart", resourceRoot,
	function()
		if (isEnabled) then
			local dmv = createPed(150, 359.29, 173.56, 1008.88, -90)
			setElementInterior(dmv, 3)
			setElementDimension(dmv, 281)
			setTimer(setPedAnimation, 100, 1, dmv, "FOOD", "FF_Sit_Look", -1, true, false, false, true)
			setTimer(setPedAnimation, 5000, 0, dmv, "FOOD", "FF_Sit_Look", -1, true, false, false, true)
			setElementData(dmv, "roleplay:dmv.element", 1, false)
			setElementData(dmv, "roleplay:peds.name", "Elizabeth_Harris", false)
		end

------ CODE END ----

Check this 3 nodes.: 
			local dmv = createPed(150, 359.29, 173.56, 1008.88, -90)
			setElementInterior(dmv, 3)
			setElementDimension(dmv, 281)

are they correct? it seems that it's on dimension 281. shouldn't it be zero?
ElementInterior should be 3?
createPed is with strange coordinates. are they correct?


THANKS FOR THE QUICK ANSWERS!!!
If anything more i'll edit this post to add more questions :) until that.. cheers bro

**Comment by Socialz** [comment]
1. I'll have a quick look at it and see if there is anything I can do.
2. You have to change the coordinates, interior and dimension to inside of your current one. Use /getpos to get the information.
3. The way it stores the phone numbers is as the `value`.
4. Use the following version to have it set to 100 units.

```lua
blips = { }

--SPAWN INICIAL
table.insert( blips, table.insert( blips, createBlip(  1722.74, -1912.21, 13.56, 56 ) ) -- SPAWN LS

-- GOV
table.insert( blips, createBlip( 1558.08, -1675.29, 28.39, 30 ) ) -- LS Police Department
table.insert( blips, createBlip( 1419.08, -1553.65, 13.56, 52 ) ) -- LS Bank
table.insert( blips, createBlip( 1480.95, -1772.07, 18.79, 41 ) ) -- LS City Hall
table.insert( blips, createBlip( 1451.63, -2287.03, 13.54, 5 ) ) -- LS Airport
table.insert( blips, createBlip( 933.13, -1720.93, 13.54, 36 ) ) -- LS DMV
table.insert( blips, createBlip( -1604.7, 710.29, 48.93, 30 ) ) -- SF POLICE

-- BOMBAS
table.insert( blips, createBlip( 1003.6298, -934.7626, 17, 53 ) ) -- LS
table.insert( blips, createBlip( 1941.7437, -1776.2634, 17, 53 ) ) -- LS
table.insert( blips, createBlip( -91.59, -1169.35, 3.84, 53 ) ) -- LS
table.insert( blips, createBlip( 655.57, -564.47, 16.33, 53 ) ) -- Dillimore
table.insert( blips, createBlip( 1380.34, 456.91, 19.89, 53 ) ) -- MONTGOMERY
table.insert( blips, createBlip( -2244.06, -2560.74, 31.92, 53 ) ) -- Angel Pine
table.insert( blips, createBlip( -1606.16, -2713.86, 48.53, 53 ) ) -- Auto Estrada LS - SF

-- LOJAS
table.insert( blips, createBlip( 1841.2701, -1842.9167, 17, 17 ) ) -- LS
table.insert( blips, createBlip( 1329.6690, -1635.4135, 17, 17 ) ) -- LS
table.insert( blips, createBlip( 1584.2709, -1180.0893, 17, 17 ) ) -- LS
table.insert( blips, createBlip( 1398.7307, -1881.4731, 17, 17 ) ) -- LS
table.insert( blips, createBlip( 2429.39, -1748.19, 17, 17 ) ) -- LS
table.insert( blips, createBlip( 992.1, -1290.28, 17.38, 17 ) ) -- LS
table.insert( blips, createBlip( 1315.43, -891.41, 45.22, 17 ) ) -- LS
table.insert( blips, createBlip( 2665.47, -1100.03, 75.71, 17 ) ) -- LS
table.insert( blips, createBlip( 816.6, -552.57, 20.33, 17 ) ) -- Dillimore
table.insert( blips, createBlip( 1260.72, 278.19, 23.55, 17 ) ) -- MONTGOMERY
table.insert( blips, createBlip( 2244.18, 57.11, 32.48, 17 ) ) -- PALOMINO CREEK
table.insert( blips, createBlip( 252.3, -54.83, 1.57, 17 ) ) -- BLUEBERRY

-- HOUSING
table.insert( blips, createBlip( 2314.87, -1792.55, 21.89, 31 ) ) -- LS
table.insert( blips, createBlip( 2353.37, -1050, 54.06, 31 ) ) -- LS
table.insert( blips, createBlip( 2487.32, -1042.73, 71.35, 31 ) ) -- LS
table.insert( blips, createBlip( 916.96, -1648.02, 30.46, 31 ) ) -- LS
table.insert( blips, createBlip( 854.9, -1493.58, 70.78, 31 ) ) -- LS
table.insert( blips, createBlip( 786.28, -527.21, 42.96, 31 ) ) -- DILLIMORE
table.insert( blips, createBlip( 1294.12, 163.64, 48.54, 31 ) ) -- MONTGOMERY
table.insert( blips, createBlip( 2365.09, 45.75, 64.01, 31 ) ) -- PALOMINO CREEK
table.insert( blips, createBlip( 249.98, -297.56, 33.33, 31 ) ) -- BlueBerry
table.insert( blips, createBlip( 184.33, -107.9, 23.59, 31 ) ) -- BlueBerry Apts
table.insert( blips, createBlip( -2201.45, -2481.77, 44.01, 31 ) ) -- Angel Pine
table.insert( blips, createBlip( -2069.44, -2525.28, 69.74, 31 ) ) -- Angel Pine Roulotes


-- HOTELS
table.insert( blips, createBlip( 2204.44, -1142.09, 33.53, 32 ) ) -- LS
table.insert( blips, createBlip( 475.82, -1498.59, 20.47, 32 ) ) -- LS

-- CASA MITICA
table.insert( blips, createBlip( 2496.45, -1686.56, 13.3, 32 ) ) -- CJ HOUSE

-- HOSPITAIS
table.insert( blips, createBlip( 2035.91, -1404.28, 17.1, 22 ) ) -- LS HOSPITAL 1
table.insert( blips, createBlip( 1172.31, -1323.57, 15.4, 22 ) ) -- LS HOSPITAL 2

-- RESTAURANTE
table.insert( blips, createBlip( 802.93, -1618.58, 19.53, 10 ) ) -- Burgershot - LS
table.insert( blips, createBlip( 1198.36, -909.74, 48.06, 10 ) ) -- Burgershot - LS
table.insert( blips, createBlip( 2114.82, -1807.17, 22.21, 29 ) ) -- Pizza LS
table.insert( blips, createBlip( 2411.38, -1500.96, 31.9, 14 ) ) -- Chicken - LS
table.insert( blips, createBlip( 935.97, -1370.1, 23.07, 14 ) ) -- Chicken - LS
table.insert( blips, createBlip( 2391.16, -1907.15, 21.46, 14 ) ) -- Chicken - LS
table.insert( blips, createBlip( 681.14, -465.46, 22.57, 10 ) ) -- RESTAURANTE DILLIMORE
table.insert( blips, createBlip( 1373.38, 246.11, 28.21, 29 ) ) -- Montgomery PIZZA
table.insert( blips, createBlip( 2329.53, 74.53, 32, 29 ) ) -- Palomino Creek
table.insert( blips, createBlip( 205.94, -195.33, 7.57, 29 ) ) -- BlueBerry
table.insert( blips, createBlip( -2152.73, -2457.55, 35.31, 14 ) ) -- Angel Pine Chicken

for _, blip in ipairs( blips ) do
    setBlipVisibleDistance( blip, 100 )
end
```

5. You do not need to open any file. Just make a new file, do your mapping, save it as something. Then put the map to the server and execute **/refreshall** command. Then start that resource that is holding the resource. You can put the resource to your **mtaserver.conf** file as well, so the map will always start when you restart your server.

**Comment by AlphabetoPT** [comment]
Good Morning my friend. Hope i can call you that now :)
Regarding to phone bug i was watching the SQL tables and i found the row you were talking about in inventory table. However i noticed that in here every number starts by Zero. When you open the inventory and click on your phone your number never starts by zero. Also the GUI does not allow you to store contacts starting by zero. Something to do with the configuration? Maybe its set to int on lua file and it does not assume the first zero? (on sql its set to varchar so its not the source of problem.)

See u soon.

**Comment by Socialz** [comment]
You can make a DMV vehicle with /makecivveh [model id] 3.

I applied a quick fix for the roleplay-phone resource. Re-download that and see if it works :-)

**Comment by AlphabetoPT** [comment]
I love you bro!! ahahah
i'll be right back with feedback :)

**Comment by AlphabetoPT** [comment]
Almos bro :) 
Now i can dial and other player receive call.
He can pickup however we cant talk in a call. I assume you disabled /p and i guess this command is missing to communicate over phone.
We are able to send SMS. and thats a huge WIN :D 

Phone calls or SMS are not spending money to players, i'm not sure if this is your idea but it would be awesome if we pay by character on SMS and by time (seconds) over call.

Still we are unable to save the correct number into contacts since the first zero is not assumed.
I guess that now its SQL fault because its set as INT and it should be as VARCHAR i guess. what do you think?

Regards.

**Comment by Socialz** [comment]
Phone calls and SMS do not spend money, no. You have to implement that yourself. Phone talk command can be found inside the **roleplay-chat/s_chat.lua** file. I do not know if it works, you can look into it and see what /debugscript 3 returns (any errors, warnings).

I fixed the database dump. Please change your contacts' table phone number fields to varchar(10) instead.

**Comment by AlphabetoPT** [comment]
When i try to use /p or simillar during phone call it gets an error on the console..:
[18:02:46] ERROR: roleplay-chat/s_chat.lua:587: attempt to perform arithmetic on
global 'r' (a nil value)


when i try to use debugscript it says ACL negate this permission.
What resource should i add on acl to make this work?
Im sorry bro. i know i am a pain in the ass.
I'll make it up to you some how :)

**Comment by Socialz** [comment]
Re-download the roleplay-chat resource. It was trying to define some RGB values even though it had nothing to get the original values from, removed it completely since there is no need for distance coloring over phone.

**Comment by AlphabetoPT** [comment]
Working !! :D Just one little thing. On the cellphone menu it keeps the 5 digit number instead of 6. The first zero does not show. cant find where it's the mistake.

**Comment by Socialz** [comment]
Are you sure you downloaded the whole roleplay-phone resource when I updated it? I did change the client-side file to be compatible as well.

**Comment by AlphabetoPT** [comment]
Yeap. I did.
I will re-do it after dinner.
Im gonna be a DAD dude.. just found that ahahaha. WTF
Need to celebrate.

Will be here soon.
Once again thanks for all :D

**Comment by Socialz** [comment]
https://youtu.be/fyEThSM4JnI?t=1m9s

**Comment by AlphabetoPT** [comment]
Well that was close enough to my reaction dude. well a mix between this and 'that'.
I feel kinda too young to this but... not too much lol. 27 summers. Let's see what's down this road.  xD
I believe that im gonna be ok. xD

I'll try that in a few minutes and i'll leave feedback.
Once again. Thanks.

By the Way, you are not even my real friend and you were the first one to know LOL. 
AHAHAHA Anonymously there's no lies :P

**Comment by AlphabetoPT** [comment]
I am using other interiors from fairplay-roleplay. it will bug. wont it?

**Comment by AlphabetoPT** [comment]
Sorry for the delay.
I was kinda busy.
Nope. CellPhone is still with 5 digit number on the display. However it works i shall say.
If you can't find a solution for this i may add to rules something like this ''You must use 0 as first digit for cellphone."

Let me notice you that i am now officially merging some resources from GTW - RPG because it has some serious scripts. Hope you dont mind :)

**Comment by Socialz** [comment]
Try the latest version of roleplay-phone now. I updated the s_phone.lua file, should fix a few other problems as well.

You can merge resources in whatever way you wish, just let me remind you that I do not support problems in the merge or so forth; only if related to the core code of this gamemode.

**Comment by AlphabetoPT** [comment]
Ofc bro. 
I will not bother you with problems that come up due to merge other codes or with other scripts. :)
I feel bad already for being every day 'on your shoes'. 

However, i was hoping, i must admit, that you could find a spare time just to show me the guidlines to code my own jobs script. simple one for start...just to give some action to beta testers on server. 
Ofc i know you will probably will have time or the will to help a stranger out :)

I noticed that on MTA community it's common that server owners pay scripters for work.
Never happened on Minecraft server. I must say... 
Im not sure if this is a good or bad thing. still figuring it out. 

I will test it and then post a new comment out with feedback.
Cheers

**Comment by AlphabetoPT** [comment]
Need Help.:

makeveh and makecivveh are not spawning cars after the save. They are into sql well saved however they just don't spawn. Note.: this is reported only today but vehicles were saved and missing before installing new scripts.
Plus the script i am using in addition is only messing with interiors and peds.

**Comment by Socialz** [comment]
1. What do you mean?
2. I do not know about this and I am not really keen to look into it either.
3. You can enable this at the same place as earlier *(roleplay-accounts/s_accounts.lua:625), by adding this line:
```lua
setPlayerHudComponentVisible( client, "crosshair", true )
```
