### ISSUE TITLE
What am I supposed to do?

### ISSUE THREAD

**Issue by peppinoita** [Socialz/lua-mta-fairplay#17]
Hi and thanks for your job!
I'm enjoying to test several mods on my  pc and this seems very beautiful and powerful.
I installed everything without any problem, but I can't find any working blips on the map.
If I go to the city hall is is supposed to access and choose a job right?
Instead nothing happens, there is nothing working in the City?
Am I missing something?

**Comment by Socialz** [comment]
You are supposed to use the admin commands to set up everything yourself. You need to have basic ability to edit the code, so in this case to get the City Hall peds you need to edit the *roleplay-jobs/c_jobs.lua* file and set the coordinates for the ped.

You can view the admin commands by typing /ah in-game.

**Comment by peppinoita** [comment]
Thanks for the reply.
If I can abuse of your time, can I ask another thing?
In that file there is:
	function()
		local cityPed = createPed(141, 1465.51, -1777.98, 1251.42, 180)
		setElementInterior(cityPed, 4)
		setElementDimension(cityPed, 15)
		setElementData(cityPed, "roleplay:jobs.ped", true, false)
		setElementData(cityPed, "roleplay:peds.name", "Selena_Rodriguez", false)
		setTimer(setPedAnimation, 100, 1, cityPed, "FOOD", "FF_Sit_Look", -1, true, false, false, true)
		setTimer(setPedAnimation, 5000, 0, cityPed, "FOOD", "FF_Sit_Look", -1, true, false, false, true)
		setTimer(setElementPosition, 20000, 0, cityPed, 1465.51, -1777.98, 1251.42)
		triggerEvent(":_loadRealJobs_:", localPlayer)
	end

But if I replace the positions, interior and dimension with mine and reload the resource nothing happens.

Can I ask you if you have a pre-populated db and files with the right info to start learning?

Thanks again

**Comment by Socialz** [comment]
That should do the trick if you put them on correctly. Check /debugscript 3 and see if there are any errors going on.

As for what goes to the pre-populated database, I do not have it. This is an old gamemode and I am already half-way through working on a [new version of this](https://github.com/Socialz/lua-mta-fairplay-roleplay).

**Comment by peppinoita** [comment]
Thanks I will try the new version

**Comment by Socialz** [comment]
Note however, that that version is still under development and is missing a lot of features. If you have no problem waiting, then that's good. Otherwise, I'd probably go for this old version and fix it, or then try another gamemode like [Paradise](https://github.com/Socialz/mta-paradise) (which is finished and well done).
