### ISSUE TITLE
Fail to Download Resources

### ISSUE THREAD

**Issue by AlphabetoPT** [Socialz/lua-mta-fairplay#20]
Hello.
Not sure if you remember me but i am back at MTA scripting.
I have now a team to start an RP project based on your scripts.
However there's a little problem, maybe due to MTA 1.5.
Right before the ending of the resource download it stops. and pop's up a window stating that is not possible to make the download.
Any clues?

Thanks

**Comment by Socialz** [comment]
Resource download problems are caused by the MTA client/server communication. I cannot help with that, as there can be a dozen reasons why that happens.

Try clearing your client MTA resources folder and reconnecting to the server. Should also try to clear server cache files.
