### ISSUE TITLE
Black Screen, Help.

### ISSUE THREAD

**Issue by KAPAspeed** [Socialz/lua-mta-fairplay#21]
So hi, i just waned to start a roleplay server so i download this script, when i started the server it sayed download 14,30 mb then it wash only black screen can you help? (if something is written wrong, sry.) and there are some errors in the cmd.

**Comment by KAPAspeed** [comment]
Here is a pictchure for the balack screen so you get an idea what im dealing with: http://prntscr.com/9sla36

**Comment by Socialz** [comment]
You have no database connection.

**Comment by KAPAspeed** [comment]
how can i do that?
