### ISSUE TITLE
I can´t create faction vehicles

### ISSUE THREAD

**Issue by PabletoRG** [Socialz/lua-mta-fairplay#22]
Hello, i starting to translate your Gamemode (Thanks for creating it) and, i can´t create faction vehicles, and the console show me this 

> ERROR: roleplay-admin\s_vehicle_admin.lua:155: attempt to compare nil with number
How i can fix it?

greetings

**Comment by Socialz** [comment]
Hey,

Thanks for reporting the error, I have fixed that bug now.

Replace **roleplay-factions/s_factions.lua** with this file's contents https://raw.githubusercontent.com/Socialz/lua-mta-fairplay/fbaf6a732c6f55eb6c30dc8a06c73aa3249faf9c/resources/roleplay-factions/s_factions.lua

Let me know if that works for you.

**Comment by PabletoRG** [comment]
Nope, ain´t work, the console show me the same message :(

> [2016-02-26 14:32:21] ERROR: roleplay-admin\s_vehicle_admin.lua:155: attempt to compare nil with number

**Comment by Socialz** [comment]
Did you restart the resource `roleplay-factions`?

**Comment by PabletoRG** [comment]
Yes, i restarted the server in general, and doesn´t work, and, the TAB
button doesn´t work too :(

2016-02-26 18:18 GMT-03:00 Socialz <notifications@github.com>:

> Did you restart the resource roleplay-factions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Socialz/lua-mta-fairplay/issues/22#issuecomment-189486413>
> .
>



-- 
Pablo Patricio Mieres González
       *Guitarrista ritmico y compositor.*

**Comment by Socialz** [comment]
Okay.

Replace **roleplay-admin/s_vehicle_admin.lua** with this file's contents https://raw.githubusercontent.com/Socialz/lua-mta-fairplay/423dde8574242685a9a96645bc507c298afbcb50/resources/roleplay-admin/s_vehicle_admin.lua

Let me know if that fixes the faction bug.
