### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Jabern** [Socialz/lua-mta-fairplay#23]
Hi , Why they have compiled file ?

**Comment by Socialz** [comment]
What file?

**Comment by Jabern** [comment]
c_streets.luac

and 

c_vehiclenodes.luac

ps : i respect you'r job :) and the Gamemode are verry cool ;) i devlop him for frensh community

**Comment by Socialz** [comment]
Those files are huge, that's why they've been compiled, much faster that way.

You can use the vehicle nodes from the [default MTA **gps** resource](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Bgameplay%5D/gps/vehiclenodes.lua), that's where it is from anyway.

As for the streets.luac, I don't have it anymore, but I found a close copy which might work.
https://gist.github.com/Socialz/6e52a90182baa010e5084c648bc76994

**Comment by Jabern** [comment]
Thank for the information , :+1: :)

Another thing , i cant display faction panel (F1) without restart res :/

**Comment by Socialz** [comment]
Jup, I know that bug. Can't fix it at the moment but maybe some time.

**Comment by Jabern** [comment]
Ok :/ Contact me if you fix it beacause i dév you'r GameMode and i fix scoreboard but not this.

if you can tell me how fix it or just function ho have a problem :)

Thanx :)

**Comment by Socialz** [comment]
Try the latest version now.

https://github.com/Socialz/lua-mta-fairplay/commit/428b6ebd422594537764533583f78fa2483b7692

**Comment by Jabern** [comment]
I download just the : roleplay-factions ?

**Comment by Jabern** [comment]
It's work thanks , another problem ^^ 

ERROR: roleplay-chat/s_chat.lua:875: attempt to concatenate a boolean value

**Comment by Jabern** [comment]
getAdminRank bug :/

**Comment by Socialz** [comment]
What is your admin level?

**Comment by Socialz** [comment]
Try the latest version now. I am pretty sure it's because you are a power user and not a real admin, and power user had no rank title.

https://github.com/Socialz/lua-mta-fairplay/commit/5666b283651723708923796b47befc2cb295d5bd

Let me know if that works.

**Comment by Jabern** [comment]
I fix it , you have an error you need to try this ;) 

`tostring(exports['roleplay-accounts']:getAdminRank`

beacause `getAdminRank `generate a boolean value

**Comment by Socialz** [comment]
It will generate a boolean value in these cases:
* Admin level is not a number
* Admin level is under 0
* Admin level is over 6
* User is also not a power user

Other cases, no.

**Comment by Jabern** [comment]
Ahhh i understand x) i give me the Level 8 :"D any way .... Thank you a lot for reading my message and response , i complet the GameMode :+1:  :+1:

Another thing : Ther'is no longer update ?

**Comment by Socialz** [comment]
No problem.

Yes, this gamemode is old and obsolete. There's a new one I've been doing for almost 2 years now, but haven't released it yet. I also started to work on an object-oriented roleplay gamemode just recently, but it's currently very limited and still very early in development (https://github.com/Socialz/lua-mta-roleplay-oop).
