### ISSUE TITLE
Coroutine

### ISSUE THREAD

**Issue by Jabern** [Socialz/lua-mta-fairplay#24]
Hi SocialZ i Have an error with coroutine.resume 

ERROR: roleplay-interiors\s_interiors.lua:619: cannot resume dead coroutine [string "?"]  [DUP x15]

**Comment by Socialz** [comment]
https://github.com/Socialz/lua-mta-fairplay/commit/6c3ca09f093b09fadd221649b872a556f22d5c43

Download the new version of s_interiors.lua now, should be fixed.

**Comment by Jabern** [comment]
Can you explain ^^ cause i'm very curious how you fix the coroutine bug ^^

**Comment by Socialz** [comment]
I made bad code, less bad. That's all.
